const { model, Schema } = require("mongoose");

const childFormSchema = new Schema({
  userId: String,
  gender: String,
  name: String,
  email: String,
  dateOfBirth: String,
  primaryLanguage: String,
  education: String,
  history: String,
  problem: String,
  broSis: String,
  impaired: String,
  impairment: String,
  schoolLanguage: String,
  reason: String,
  improvement: String,
  awareness: String,
  institute: String,
  treatment: String,
  teacherFeedback: String,
  teacherFeedback1: String,
  walkingAge: String,
  speakingAge: String,
  speakingAgeSentence: String,
  developmentProblem: String,
  developmentProblem1: String,
  muscleProblem: String,
  muscleProblem1: String,
  illnessAtBirth: String,
  illnessAtBirth1: String,
  illness: String,
  illness1: String,
  surgery: String,
  surgery1: String,
  medication: String,
  medication1: String,
  familyHistory: String,
  familyMember: String,
  educationScore: String,
  developmentScore: String,
  illnessScore: String,
  familyScore: String,
  createdAt: String,
});

module.exports = model("ChildForm", childFormSchema);
